management:
  security:  
    enabled: false  
    
spring:
    
  application:
    name: shoc-webgtw
    
  cloud: 
    gateway:
        
      routes:
      - id: shoc-builder
        uri: ${SHOC_BUILDER_URI:http://localhost:11006/}
        predicates:
        - Path=/shoc-builder/**
        filters:
        - StripPrefix=1
        
      x-forwarded:
        prefix-enabled: false
    
server:
  port: 11002
  connection-timeout: 900000
  http2:
      enabled: true
  compression:
      enabled: true
      mime-types: application/json


