version: '3.5'

volumes: 
  shoc-database-sql-volume:
    name: "shoc-database-sql-volume"
  shoc-dind-data-volume:
    name: "shoc-dind-data-volume"

networks:
  shoc-network:
    name: shoc-network

services:   
  
  shoc-database-sql:
    image: shoc-database-sql:latest
    restart: always
    build: ./Shoc.Database.Sql
    container_name: shoc-database-sql
    env_file: 
      - ./env/shoc-database-sql.env
    ports:
      - '11001:11001'
    networks:
      - shoc-network
    volumes:
      - shoc-database-sql-volume:/var/lib/mysql 

  shoc-database-migrator:
    image: shoc-database-migrator:latest
    build: ./Shoc.Database.Migrator
    container_name: shoc-database-migrator
    restart: "no"
    ports:
      - '11010:11010'
    env_file:
      - ./env/ref-database-sql.env
      - ./env/ref-api-discovery.env
      - ./env/shoc-database-migrator.env
    depends_on:
      - shoc-database-sql
    networks:
      - shoc-network
      
  shoc-dind:
    image: shoc-dind:latest
    build: ./Shoc.Dind
    restart: always
    container_name: shoc-dind
    privileged: true
    ports:
      - '11003:11003'
    networks:
      - shoc-network
    volumes:
      - shoc-dind-data-volume:/var/lib/docker

  shoc-builder:
    image: shoc-builder:latest
    restart: always
    build: ./Shoc.Builder
    container_name: shoc-builder
    env_file: 
      - ./env/ref-api-auth.env
      - ./env/ref-api-discovery.env
      - ./env/ref-database-sql.env
      - ./env/ref-dind.env
      - ./env/shoc-builder.env
    ports:
      - '11006:11006'
    depends_on:
      - shoc-database-sql
      - shoc-dind
    networks:
      - shoc-network
      
  shoc-identity:
    image: shoc-identity:latest
    restart: always
    build: ./Shoc.Identity
    container_name: shoc-identity
    env_file: 
      - ./env/ref-api-auth.env
      - ./env/ref-api-discovery.env
      - ./env/ref-database-sql.env
      - ./env/ref-mailing.env
      - ./env/shoc-identity.env
    ports:
      - '11008:11008'
    depends_on:
      - shoc-database-sql
    networks:
      - shoc-network
      
  shoc-executor:
    image: shoc-executor:latest
    restart: always
    build: ./Shoc.Executor
    container_name: shoc-executor
    env_file: 
      - ./env/ref-api-auth.env
      - ./env/ref-api-discovery.env
      - ./env/ref-database-sql.env
      - ./env/shoc-executor.env
    ports:
      - '11012:11012'
    depends_on:
      - shoc-database-sql
    networks:
      - shoc-network
      
  shoc-webgtw:
    image: shoc-webgtw:latest
    restart: always
    build: ./Shoc.Webgtw
    container_name: shoc-webgtw
    env_file: 
      - ./env/ref-api-discovery.env
      - ./env/shoc-webgtw.env
    ports:
      - '11002:11002'
    depends_on:
      - shoc-builder
    networks:
      - shoc-network
      
  shoc-ingress:
    image: shoc-ingress
    build: ./Shoc.Ingress
    container_name: shoc-ingress
    hostname: shoc.local
    restart: always
    ports:
      - '11000:11000'
    depends_on:
      - shoc-webgtw
      - shoc-identity
    networks:
      shoc-network:
        aliases:
         - identity.shoc.local
         - api.shoc.local
   
