volumes: 
  shoc-database-volume:
    name: "shoc-database-volume"
  shoc-dind-data-volume:
    name: "shoc-dind-data-volume"
  shoc-kind-data-volume:
    name: "shoc-kind-data-volume"

networks:
  shoc-network:
    name: shoc-network

services:   
  
  shoc-database:
    image: ${SHOC_PUBLIC_REGISTRY:-ghcr.io}/${SHOC_PUBLIC_REPOSITORY:-imastio/shoc/public}/shoc-database:${SHOC_PUBLIC_VERSION:-latest}
    restart: always
    build: ./infrastructure/Shoc.Database
    container_name: shoc-database
    env_file: 
      - ./env/shoc-database.env
    ports:
      - '11001:11001'
    networks:
      - shoc-network
    volumes:
      - shoc-database-volume:/var/lib/mysql 

  shoc-dind:
    image: ${SHOC_PUBLIC_REGISTRY:-ghcr.io}/${SHOC_PUBLIC_REPOSITORY:-imastio/shoc/public}/shoc-dind:${SHOC_PUBLIC_VERSION:-latest}
    build: ./infrastructure/Shoc.Dind
    restart: always
    container_name: shoc-dind
    privileged: true
    ports:
      - '11006:11006'
    networks:
      - shoc-network
    volumes:
      - shoc-dind-data-volume:/var/lib/docker

  shoc-kind:
    image: ${SHOC_PUBLIC_REGISTRY:-ghcr.io}/${SHOC_PUBLIC_REPOSITORY:-imastio/shoc/public}/shoc-kind:${SHOC_PUBLIC_VERSION:-latest}
    build: ./infrastructure/Shoc.Kind
    restart: always
    container_name: shoc-kind
    privileged: true
    ports:
      - '11008:11008'
    env_file:
      - ./env/shoc-kind.env
    networks:
      - shoc-network
    volumes:
      - shoc-kind-data-volume:/var/lib/rancher/k3s

  shoc-database-migrator:
    image: ${SHOC_PUBLIC_REGISTRY:-ghcr.io}/${SHOC_PUBLIC_REPOSITORY:-imastio/shoc/public}/shoc-database-migrator:${SHOC_PUBLIC_VERSION:-latest}
    build: ./apps/shoc-database-migrator/Shoc.Database.Migrator
    container_name: shoc-database-migrator
    restart: "no"
    ports:
      - '11012:11012'
    env_file:
      - ./env/ref-api-datasource.env
      - ./env/ref-api-discovery.env
      - ./env/shoc-database-migrator.env
    depends_on:
      - shoc-database
    networks:
      - shoc-network

  shoc-identity:
    image: ${SHOC_PUBLIC_REGISTRY:-ghcr.io}/${SHOC_PUBLIC_REPOSITORY:-imastio/shoc/public}/shoc-identity:${SHOC_PUBLIC_VERSION:-latest}
    restart: always
    build: ./apps/shoc-identity/Shoc.Identity
    container_name: shoc-identity
    env_file: 
      - ./env/ref-api-auth.env
      - ./env/ref-api-discovery.env
      - ./env/ref-api-datasource.env
      - ./env/ref-api-mailing.env
      - ./env/shoc-identity-provider.env
      - ./env/shoc-identity.env
    ports:
      - '11014:11014'
    depends_on:
      - shoc-database
    networks:
      - shoc-network

  shoc-webgtw:
    image: ${SHOC_PUBLIC_REGISTRY:-ghcr.io}/${SHOC_PUBLIC_REPOSITORY:-imastio/shoc/public}/shoc-webgtw:${SHOC_PUBLIC_VERSION:-latest}
    restart: always
    build: ./apps/shoc-webgtw/Shoc.Webgtw
    container_name: shoc-webgtw
    env_file: 
      - ./env/ref-api-auth.env
      - ./env/ref-api-discovery.env
      - ./env/shoc-webgtw.env
    ports:
      - '11010:11010'
    networks:
      - shoc-network

  shoc-ingress:
    image: ${SHOC_PUBLIC_REGISTRY:-ghcr.io}/${SHOC_PUBLIC_REPOSITORY:-imastio/shoc/public}/shoc-ingress:${SHOC_PUBLIC_VERSION:-latest}
    build: ./infrastructure/Shoc.Ingress
    container_name: shoc-ingress
    hostname: shoc.local
    restart: always
    ports:
      - '11000:11000'
    depends_on:
      - shoc-identity
    networks:
      shoc-network:
        aliases:
         - shoc.local
         - identity.shoc.local
         - api.shoc.local
         - cr.shoc.local
         - admin.shoc.local