version: '3.5'

volumes: 
  shoc-database-sql-volume:
    name: "shoc-database-sql-volume"
  shoc-dind-data-volume:
    name: "shoc-dind-data-volume"
  shoc-docker-registry-volume:
    name: "shoc-docker-registry-volume"  

networks:
  shoc-network:
    name: shoc-network

services:   
  
  shoc-database-sql:
    image: shoc-database-sql:latest
    restart: always
    build: ./Shoc.Database.Sql
    container_name: shoc-database-sql
    env_file: 
      - ./env/setup-database-sql.env
    ports:
      - '11001:11001'
    networks:
      - shoc-network
    volumes:
      - shoc-database-sql-volume:/var/lib/mysql 
      
  shoc-docker-registry:
    image: shoc-docker-registry:latest
    restart: always
    build: ./Shoc.Docker.Registry
    container_name: shoc-docker-registry
    env_file: 
      - ./env/setup-docker-registry.env
    ports:
      - '11004:11004'
    networks:
      - shoc-network
    volumes:
      - shoc-docker-registry-volume:/var/lib/registry

  shoc-dind:
    image: shoc-dind:latest
    build: ./Shoc.Dind
    restart: always
    container_name: shoc-dind
    privileged: true
    ports:
      - '11003:11003'
    networks:
      - shoc-network
    volumes:
      - shoc-dind-data-volume:/var/lib/docker

  shoc-builder:
    image: shoc-builder:latest
    restart: always
    build: ./Shoc.Builder
    container_name: shoc-builder
    env_file: 
      - ./env/ref-api-discovery.env
      - ./env/ref-database-sql.env
      - ./env/ref-dind.env
      - ./env/ref-docker-registry.env
    ports:
      - '11006:11006'
    depends_on:
      - shoc-database-sql
      - shoc-docker-registry
      - shoc-dind
    networks:
      - shoc-network
      
  shoc-webgtw:
    image: shoc-webgtw:latest
    restart: always
    build: ./Shoc.Webgtw
    container_name: shoc-webgtw
    env_file: 
      - ./env/ref-java.env
      - ./env/webgtw.env
    ports:
      - '11000:11000'
    depends_on:
      - shoc-builder
    networks:
      - shoc-network
   
