volumes: 
  shoc-database-volume:
    name: "shoc-database-volume"

networks:
  shoc-network:
    name: shoc-network

services:   
  
  shoc-database:
    image: ${SHOC_PUBLIC_REGISTRY:-ghcr.io}/${SHOC_PUBLIC_REPOSITORY:-imastio/shoc/public}/shoc-database:${SHOC_PUBLIC_VERSION:-latest}
    restart: always
    build: ./infrastructure/Shoc.Database
    container_name: shoc-database
    env_file: 
      - ./env/shoc-database.env
    ports:
      - '11001:11001'
    networks:
      - shoc-network
    volumes:
      - shoc-database-volume:/var/lib/mysql 
