apiVersion: v1
kind: Service
metadata:
  name: shoc-executor
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 11012
      targetPort: 11012
  selector:
    app: shoc-executor