registry:
  dockerConfigJson: ${SHOC_REGISTRY_DOCKER_CONFIG_JSON}
  registry: ${SHOC_PUBLIC_REGISTRY}
  repository: ${SHOC_PUBLIC_REPOSITORY}
  publicVersion: ${SHOC_PUBLIC_VERSION}
  pullPolicy: Always

addresses:
  root: shoc.asnet.am
  api: api.shoc.asnet.am
  identity: identity.shoc.asnet.am

discovery:
  primary: static
  fallback: gateway
  static:
    host: 
  gateway:
    gateway: 

database:
  username: ${SHOC_DATABASE_USERNAME}
  password: ${SHOC_DATABASE_PASSWORD}
  name: shoc

dind:
  clientAddress: tcp://shoc-dind:11003

identity:
  machine:
    clientId: ${SHOC_IDENTITY_CLIENT_ID}
    clientSecret: ${SHOC_IDENTITY_CLIENT_SECRET}
  interactive:
    tokenExpiration: 3600
  google:
    clientId: ${SHOC_IDENTITY_GOOGLE_CLIENT_ID}
    clientSecret: ${SHOC_IDENTITY_GOOGLE_CLIENT_SECRET}
