apiVersion: v1
kind: PersistentVolume
metadata:
  name: shoc-cr-storage-pv
  labels:
    volume-type: ssd
    use-for: shoc-cr
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shoc-local-storage-class
  local:
    path: /volumes/shoc-cr-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: shoc-cr-host
          operator: In
          values:
          - shoc-cr-host