apiVersion: v1
kind: Service
metadata:
  name: shoc-identity
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 11008
      targetPort: 11008
  selector:
    app: shoc-identity