apiVersion: v1
kind: Service
metadata:
  name: shoc-builder
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 11006
      targetPort: 11006
  selector:
    app: shoc-builder