apiVersion: v1
kind: Service
metadata:
  name: shoc-database-sql
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 11001
      targetPort: 11001
  selector:
    app: shoc-database-sql