name: Deploy Container Registry

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set the Kubernetes context
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.SHOC_K8S_KUBECONFIG }}
        context: microk8s
        
    - name: Checkout yagen and make it executable
      run: |
        wget -O /usr/local/bin/yagen https://github.com/imastio/yagen/releases/download/v1.0.2/yagen-linux64-v1.0.2
        chmod +x /usr/local/bin/yagen
        
    - name: Deploy container registry
      shell: bash
      env:
        HTPASSWD_SECRET: ${{secrets.SHOC_DEFAULT_CR_HTPASSWD}}
      run: |
        cd kube/cr/
        envsubst < ./values/base-values.yml > ./values/base-values.yml.tmp && mv ./values/base-values.yml.tmp ./values/base-values.yml
        yagen
        cd build/prod/
        kubectl apply -f .
        