name: Deploy Container Registry

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set the Kubernetes context
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.SHOC_K8S_KUBECONFIG }}
        context: microk8s
        
    - name: List pods
      run: kubectl get pods