# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Database deployment

on:
  workflow_dispatch:
    branches: [ "main" ]

env:
  SHOC_PUBLIC_REGISTRY: ghcr.io
  SHOC_PUBLIC_REPOSITORY: ${{ github.repository }}/public
  SHOC_PUBLIC_VERSION: ${{ github.sha }}

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Build database images
      run: docker-compose build shoc-database-sql 
   
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.SHOC_PUBLIC_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.SHOC_GHCR_TOKEN }}

    - name: Push database image
      run: docker-compose push shoc-database-sql 
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout yagen and make it executable
      run: |
        wget -O /usr/local/bin/yagen https://github.com/imastio/yagen/releases/download/v1.0.2/yagen-linux64-v1.0.2
        chmod +x /usr/local/bin/yagen
        
    - name: Build kubernetes package
      shell: bash
      env:
        SHOC_PUBLIC_REGISTRY_USERNAME: ${{github.actor}}
        SHOC_PUBLIC_REGISTRY_PASSWORD: ${{secrets.SHOC_GHCR_TOKEN}}
        SHOC_PUBLIC_REGISTRY_EMAIL: ${{secrets.SHOC_PUBLIC_REGISTRY_EMAIL}}
        SHOC_DATABASE_USERNAME: ${{secrets.SHOC_DATABASE_USERNAME}}
        SHOC_DATABASE_PASSWORD: ${{secrets.SHOC_DATABASE_PASSWORD}}
        SHOC_DATABASE_ROOT_PASSWORD: ${{secrets.SHOC_DATABASE_ROOT_PASSWORD}}
      run: |
        chmod +x ./kube/scripts/gen_docker_config_json.sh
        export SHOC_REGISTRY_DOCKER_CONFIG_JSON=$(./kube/scripts/gen_docker_config_json.sh)
        cd kube/database
        envsubst < ./values/values.yml > ./values/values.yml.tmp && mv ./values/values.yml.tmp ./values/values.yml
        yagen
        
    - name: Set the Kubernetes context
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.SHOC_K8S_KUBECONFIG }}
        context: microk8s
      
    - name: Deploy common configuration
      working-directory: kube/database/build/prod/
      run: |
        kubectl apply -f ./common
        
    - name: Deploy database
      working-directory: kube/database/build/prod/
      run: |
        kubectl apply -f ./shoc-database-sql